name: 'deploy'

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: 'Deploy to Netlify'
    runs-on: ubuntu-latest
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}